name: Deployment on "main" branch admin folder push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'admin/**'
      - '!.github/**'
      - '!**/.gitignore'
      - '!**/.eslintrc.json'
      - '!**/.prettierrc.json'
      - '!**/*.md'
      - '!**/LICENSE'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI/CD
    env:
      VITE_API_URL: ${{ vars.API_URL }}
      VITE_ADMINPANEL_URL: ${{ vars.ADMINPANEL_URL }}
      VITE_APP_URL: ${{ vars.APP_URL }}

    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: VITE_API_URL,VITE_ADMINPANEL_URL,VITE_APP_URL
          script: |
            cd /var/www/javascript/pclab-admin/pclab/admin
            git pull origin main
            npm ci
            echo -e "\
              VITE_API_URL=$VITE_API_URL\n\
              VITE_ADMINPANEL_URL=$VITE_ADMINPANEL_URL\n\
              VITE_APP_URL=$VITE_APP_URL\n\
            " > .env
            rm -r dist
            npm run build
            exit
